import { Species } from '../api/types';

export interface BreedInfo {
  id: string;
  name: string;
  species: Species;
  origin: string;
  regionCategory: 'LIBYAN' | 'NORTH_AFRICAN' | 'SAHELIAN' | 'INTERNATIONAL';
  primaryPurpose: 'حليب' | 'لحم وتسمين' | 'ثنائي الغرض' | 'صوف وجلود';
  description: string;
}

export const POPULAR_BREEDS: Record<Species, BreedInfo[]> = {
  CATTLE: [
    {
      id: 'holstein',
      name: 'هولشتاين فريزيان (Holstein Friesian)',
      species: 'CATTLE',
      origin: 'هولندا / عالمي',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'حليب',
      description: 'السلالة الأولى عالمياً في إنتاج الحليب التجاري، إنتاج يومي عالي يتطلب عناية وتبريد جيد',
    },
    {
      id: 'brown_swiss',
      name: 'براون سويس (Brown Swiss)',
      species: 'CATTLE',
      origin: 'سويسرا / عالمي',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'ثنائي الغرض',
      description: 'سلالة قوية تتحمل درجات الحرارة المرتفعة، حليب غني بالبروتين ومثالي لصناعة الأجبان',
    },
    {
      id: 'montbeliarde',
      name: 'مونتبليارد (Montbéliarde)',
      species: 'CATTLE',
      origin: 'فرنسا / شمال أفريقيا',
      regionCategory: 'NORTH_AFRICAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'واسعة الانتشار في شمال أفريقيا، تجمع بين الإنتاج الوفير للحليب وجودة لحوم العجول المسمنة',
    },
    {
      id: 'simmental',
      name: 'سيمينتال / فليكفيه (Simmental / Fleckvieh)',
      species: 'CATTLE',
      origin: 'أوروبا / عالمي',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'ثنائي الغرض',
      description: 'سلالة ثنائية ممتازة، كفاءة تحويل غذائي عالية ومعدل نمو يومي ممتاز لعجول التسمين',
    },
    {
      id: 'jersey',
      name: 'جيرسي (Jersey)',
      species: 'CATTLE',
      origin: 'بريطانيا / عالمي',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'حليب',
      description: 'حجم متوسط واستهلاك علف اقتصادي مع أعلى نسبة دسم ومواد صلبة في الحليب',
    },
    {
      id: 'charolais',
      name: 'شاروليه (Charolais)',
      species: 'CATTLE',
      origin: 'فرنسا / عالمي',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'لحم وتسمين',
      description: 'سلالة تسمين عملاقة ذات بنية عضلية قوية ومعدل نمو يومي قياسي',
    },
    {
      id: 'limousin',
      name: 'ليموزين (Limousin)',
      species: 'CATTLE',
      origin: 'فرنسا / عالمي',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'لحم وتسمين',
      description: 'لحوم حمراء طرية مع نسبة تصافي عالية جداً في المسالخ وسهولة في الولادة',
    },
    {
      id: 'black_angus',
      name: 'بلاك أنجوس (Black Angus)',
      species: 'CATTLE',
      origin: 'اسكتلندا / عالمي',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'لحم وتسمين',
      description: 'لحوم رخامية عالية الجودة وسرعة تأقلم ممتازة في التغذية المكثفة',
    },
    {
      id: 'libyan_local_cattle',
      name: 'بلدي ليبي محلي (Local Libyan Cattle)',
      species: 'CATTLE',
      origin: 'ليبيا',
      regionCategory: 'LIBYAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'سلالة محلية متأقلمة مع المناخ الجاف وشح المراعي ومقاومة عالية للأمراض والمتوطنات',
    },
    {
      id: 'brown_atlas',
      name: 'بلدي مغاربي / أطلسي (Brown Atlas)',
      species: 'CATTLE',
      origin: 'شمال أفريقيا (المغرب العربي)',
      regionCategory: 'NORTH_AFRICAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'سلالة شمال أفريقية عريقة متأقلمة مع المناخ المتوسطي وشبه الجاف',
    },
  ],

  SHEEP: [
    {
      id: 'barqi_libyan',
      name: 'البرقي / البرقاوي الليبي (Barqi / Libyan Barbary)',
      species: 'SHEEP',
      origin: 'ليبيا (برقة والمنطقة الشرقية والغربية)',
      regionCategory: 'LIBYAN',
      primaryPurpose: 'لحم وتسمين',
      description: 'السلالة الوطنية الليبية الأشهر والأوسع انتشاراً؛ تمتاز بكتلة اللحم الممتازة والذيل العريض (الإلية) وقدرة تحمل الجفاف وطلب سوقي مرتفع للأضاحي',
    },
    {
      id: 'ouled_djellal',
      name: 'أولاد جلال (Ouled Djellal)',
      species: 'SHEEP',
      origin: 'الجزائر / شمال أفريقيا',
      regionCategory: 'NORTH_AFRICAN',
      primaryPurpose: 'لحم وتسمين',
      description: 'أكبر سلالات شمال أفريقيا بنية وجثة بيضاء صلبة وقوائم طويلة، سريعة النمو وتصل لأوزان قياسية في التسمين',
    },
    {
      id: 'assaf',
      name: 'العساف المحسن (Assaf)',
      species: 'SHEEP',
      origin: 'مستورد محسن / شمال أفريقيا',
      regionCategory: 'NORTH_AFRICAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'سلالة ممتازة لإنتاج الحليب بكميات وفيرة وصناعة الأجبان مع لحم ممتاز',
    },
    {
      id: 'awassi',
      name: 'العواسي / النعيمي (Awassi)',
      species: 'SHEEP',
      origin: 'المشرق العربي وشمال أفريقيا',
      regionCategory: 'NORTH_AFRICAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'رأس بني وجسم أبيض وإلية عريضة، حليب وفير ولحم مرغوب ومقاومة عالية للظروف القاسية',
    },
    {
      id: 'sardi',
      name: 'السردي (Sardi)',
      species: 'SHEEP',
      origin: 'المغرب / شمال أفريقيا',
      regionCategory: 'NORTH_AFRICAN',
      primaryPurpose: 'لحم وتسمين',
      description: 'سلالة ذات هيبة بلون أبيض وسواد حول العينين والمخطم، قرون لولبية قوية ومطلوبة للأضاحي',
    },
    {
      id: 'dman',
      name: 'الدماني (D\'man)',
      species: 'SHEEP',
      origin: 'واحات الجنوب الليبي والمغاربي',
      regionCategory: 'LIBYAN',
      primaryPurpose: 'لحم وتسمين',
      description: 'سلالة الواحات فائقة الخصوبة، تلد مرتين بالسنة وتنتج توائم متكررة (2 إلى 4 مواليد في البطن)',
    },
    {
      id: 'saqei_libyan',
      name: 'الصقعي الليبي (Saghri / Libyan Saqei)',
      species: 'SHEEP',
      origin: 'شرق وجنوب ليبيا',
      regionCategory: 'LIBYAN',
      primaryPurpose: 'لحم وتسمين',
      description: 'سلالة بادية ليبية أصيلة تمتاز بالصبر وسرعة التسمين في فترات الربيع',
    },
    {
      id: 'fulani_peul',
      name: 'الفولاني / بيل عودة (Fulani / Peul Oudah)',
      species: 'SHEEP',
      origin: 'دول الساحل الإفريقي (النيجر، تشاد، مالي، السودان)',
      regionCategory: 'SAHELIAN',
      primaryPurpose: 'لحم وتسمين',
      description: 'أشهر سلالات حزام الساحل الإفريقي وجنوب الصحراء؛ طويلة القامة، لون ثنائي مميز (نصف أمامي أسود/أحمر وخلفي أبيض)، حركة واسعة وقابلية تسمين عالية',
    },
    {
      id: 'tuareg_sahelian',
      name: 'طوارق / أزواد (Tuareg / Sahelian Sheep)',
      species: 'SHEEP',
      origin: 'الصحراء الكبرى والساحل (الجنوب الليبي، النيجر، مالي)',
      regionCategory: 'SAHELIAN',
      primaryPurpose: 'لحم وتسمين',
      description: 'سلالة الصحراء الجافة ذات أرجل طويلة وصوف أملس خفيف، أقصى درجات المقاومة للعطش والحرارة الشديدة',
    },
    {
      id: 'toubou_tibesti',
      name: 'التورغوي / تيبستي (Toubou / Tibesti)',
      species: 'SHEEP',
      origin: 'جنوب ليبيا وشمال تشاد',
      regionCategory: 'SAHELIAN',
      primaryPurpose: 'لحم وتسمين',
      description: 'متأقلمة تماماً مع التضاريس الجبلية الوعرة والمناخ الصحراوي القاسي',
    },
    {
      id: 'najdi',
      name: 'النجدي (Najdi)',
      species: 'SHEEP',
      origin: 'الجزيرة العربية',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'لحم وتسمين',
      description: 'لون أسود ورأس أبيض وشعر ناعم، قامة فارعة وبنية قوية',
    },
    {
      id: 'local_cross_sheep',
      name: 'بلدي مهجن (Local Crossbreed)',
      species: 'SHEEP',
      origin: 'محلي',
      regionCategory: 'LIBYAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'خليط محلي مستقر يجمع بين قوة التحمل والإنتاجية',
    },
  ],

  GOAT: [
    {
      id: 'libyan_local_goat',
      name: 'الماعز الليبي البلدي (Local Libyan Goat)',
      species: 'GOAT',
      origin: 'ليبيا',
      regionCategory: 'LIBYAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'الماعز الأصيل واسع الانتشار، رعي ممتاز في كافة البيئات الساحلية والصحراوية، لحم شهي وحليب مغذٍ',
    },
    {
      id: 'green_mountain_goat',
      name: 'ماعز الجبل الأخضر (Green Mountain Goat)',
      species: 'GOAT',
      origin: 'ليبيا (الجبل الأخضر والساحل الشرقي)',
      regionCategory: 'LIBYAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'سلالة متأقلمة مع بيئة الأحراش والغابات والمناطق الرطبة الباردة، حجم متوسط وإنتاج حليب جيد',
    },
    {
      id: 'fezzan_oasis_goat',
      name: 'ماعز واحات فزان (Fezzan Oasis Goat)',
      species: 'GOAT',
      origin: 'ليبيا (الجنوب وفزان)',
      regionCategory: 'LIBYAN',
      primaryPurpose: 'لحم وتسمين',
      description: 'سلالة جنوبية تتحمل حرارة الصيف الشديدة وتعتمد على أعلاف الواحات والنخيل',
    },
    {
      id: 'damascus_shami',
      name: 'الماعز الدمشقي / الشامي (Damascus / Shami)',
      species: 'GOAT',
      origin: 'الشام ومصر وشمال أفريقيا',
      regionCategory: 'NORTH_AFRICAN',
      primaryPurpose: 'حليب',
      description: 'أشهر سلالات الحليب في المنطقة العربية، حجم ضخم، آذان متدلية طويلة، خصوبة عالية وتوائم مستمرة',
    },
    {
      id: 'boer',
      name: 'ماعز البور (Boer Goat)',
      species: 'GOAT',
      origin: 'جنوب أفريقيا / عالمي',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'لحم وتسمين',
      description: 'سيد سلالات اللحم عالمياً؛ رأس بني وجسم أبيض، عضلات ممتلئة وسرعة نمو فائقة في دورات التسمين',
    },
    {
      id: 'sahelian_goat',
      name: 'ماعز الساحل / الطوارق (Sahelian Goat)',
      species: 'GOAT',
      origin: 'حزام الساحل الإفريقي (النيجر، مالي، تشاد، السودان)',
      regionCategory: 'SAHELIAN',
      primaryPurpose: 'لحم وتسمين',
      description: 'سلالة طويلة القوائم ذات وبر قصير، قادرة على قطع مسافات طويلة في الرعي في أشد البيئات جفافاً',
    },
    {
      id: 'red_maradi_sokoto',
      name: 'الماعز الأحمر / ميرادي الساحل (Red Maradi / Sokoto)',
      species: 'GOAT',
      origin: 'الساحل الإفريقي وجنوب الصحراء (النيجر ونيجيريا)',
      regionCategory: 'SAHELIAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'لون أحمر ناري مميز، إنتاج حليب غني، لحم ذو جودة عالية، وأرقى جلود الماعز عالمياً',
    },
    {
      id: 'draa_goat',
      name: 'ماعز درعة (D\'raa Goat)',
      species: 'GOAT',
      origin: 'المغرب العربي والواحات',
      regionCategory: 'NORTH_AFRICAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'سلالة واحات شمال أفريقيا تمتاز بإنتاجية حليب ممتازة وتوائم متعددة',
    },
    {
      id: 'alpine',
      name: 'الماعز الألبين (Alpine)',
      species: 'GOAT',
      origin: 'الألب الأوروبية / عالمي',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'حليب',
      description: 'إنتاج تجاري مكثف للحليب مع توازن غذائي عالي وقدرة جيدة على التأقلم',
    },
    {
      id: 'saanen',
      name: 'ماعز السانين السويسري (Saanen)',
      species: 'GOAT',
      origin: 'سويسرا / عالمي',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'حليب',
      description: 'ملكة الحليب البيضاء، إنتاج يومي وفير جداً لمشاريع مصانع ومنتجات الألبان والأجبان',
    },
    {
      id: 'anglo_nubian',
      name: 'الأنجلو-نوبيان (Anglo-Nubian)',
      species: 'GOAT',
      origin: 'بريطانيا / أصول مصرية وسودانية',
      regionCategory: 'INTERNATIONAL',
      primaryPurpose: 'ثنائي الغرض',
      description: 'آذان طويلة متدلية، حليب عالي الدسم ولحوم ممتازة وتأقلم رائع مع الأجواء الدافئة',
    },
    {
      id: 'local_cross_goat',
      name: 'بلدي مهجن (Local Crossbreed)',
      species: 'GOAT',
      origin: 'محلي',
      regionCategory: 'LIBYAN',
      primaryPurpose: 'ثنائي الغرض',
      description: 'سلالة محلية هجينة متعددة الأغراض',
    },
  ],
};

export function getBreedsForSpecies(species: Species): BreedInfo[] {
  return POPULAR_BREEDS[species] || [];
}
